### ISSUE TITLE
Taps on SneakyButton registering 2-3 times.

### ISSUE THREAD

**Issue by effxiikc** [sneakyness/SneakyInput#10]
When tapping a button, there are times the button will register 2-3 times.
Ex.
-(void) tick:(float)delta {
    if (button.active == YES) {
                  NSLog(@"Tap");
    }
}

Click the SneakyButton "Button" will cause the log to display "Tap" 2-3 times. Not sure if it's a bug or I'm implementing the class wrong.

For a fix I add "button.active = NO;" in the if statement.

**Comment by sneakyness** [comment]
Unless you can provide a compiling example .xcodeproj, I can't review your implementation or debug.

**Comment by effxiikc** [comment]
Hi Sneakyness,

I've created a sample project to show the problem. What's the best way to send you the project? Thanks.

-Kelvin

**Comment by sneakyness** [comment]
I don't care as long as I get it.

**Comment by effxiikc** [comment]
Please download the project here.

http://www.megaupload.com/?d=7A6PVS1P

**Comment by sneakyness** [comment]
I'm downloading it right now.

**Comment by sneakyness** [comment]
You're checking the active status of the button, which is only a status that notifies that the user is interacting with the button, not that the button itself is being pressed. If you're only looking to track button presses, you should be watching the value of the button instead.
