### ISSUE TITLE
autoCenter=NO; not working

### ISSUE THREAD

**Issue by ashish1405** [sneakyness/SneakyInput#13]
The autoCenter=NO; is not working because you have created new location variable in side the if condition, which is not available outside the if condition. So for any value of autoCenter the location is CGRectZero

**Comment by sneakyness** [comment]
Example code? Steps to reproduce? otherwise I don't care. As it stands, SneakyInput isn't even compatible with any recent version of CC2D.

**Comment by ashish1405** [comment]
Ok sorry for that,, below are the details
cocos2d v1.0.1
iOS SDK 5.0

``` c++
    SneakyJoystickSkinnedBase *joystickBase=[[[SneakyJoystickSkinnedBase alloc] init] autorelease];
    joystickBase.joystick=[[SneakyJoystick alloc]
                           initWithRect:joystickBaseDimensions];
    joystickBase.position=ccp(screenSize.width*.8f,screenSize.height*.082f);
    joystickBase.joystick.autoCenter=NO;
```

so even if autoCenter is set to NO. it still autocenters. Reason is inside SneakyJoystick.m, the location variable inside the if condition is a new variable and its scope ends with end brace of if

``` c++
- (void)ccTouchEnded:(UITouch *)touch withEvent:(UIEvent *)event
{
    CGPoint location = CGPointZero;
    if(!autoCenter){
        /*[remove this]CGPoint*/ location = [[CCDirector sharedDirector] convertToGL:[touch locationInView:[touch view]]];
        location = [self convertToNodeSpace:location];
    }
    [self updateVelocity:location];
}
```

**Comment by sneakyness** [comment]
I think you're accessing the variables wrong, too lazy to check, I'm still on vacation till the 5th ;)
