### ISSUE TITLE
CocoaPod

### ISSUE THREAD

**Issue by beakr** [sneakyness/SneakyInput#19]
Any hope of making a CocoaPod for this library? Would be very nice.

**Comment by sneakyness** [comment]
Somewhere, right now, @mattyohe is smiling.

**Comment by sneakyness** [comment]
_ahem_ I still think CocoaPods is :-1:, but it hasn't gone away yet. Maybe if I close my eyes for a few more years… 

(pull requests welcome, if you really think this needs it)

**Comment by mattyohe** [comment]
:poop:

**Comment by sneakyness** [comment]
Cocoapods still sucks, js
