### ISSUE TITLE
sprite position issue

### ISSUE THREAD

**Issue by ghost** [sneakyness/SneakyInput#22]
the issue happens after merged "It was modified for Cocos2D-2.1, iOS-6.1.4 and Xcode-4.6.2", run the demo project on cocos2d-iphone v2.1:

![ios 2013-10-13 12 24 44](https://f.cloud.github.com/assets/855845/1321406/745b954a-33bf-11e3-9a8c-00e012e35e76.png)

**Comment by tanis2000** [comment]
I noticed that as well.. have you solved this issue by any chance?

**Comment by tanis2000** [comment]
While I was working on porting it to cocos2d v3 I also fixed this issue. You can check it out at this PR: https://github.com/sneakyness/SneakyInput/pull/23

**Comment by sneakyness** [comment]
Thanks!
